import {test,expect} from 'vitest'
import {WorkspaceFiles} from '../src/sandbox/files'
import {FileDescriptors} from '../src/sandbox/file-descriptors'

test('read-only directory descriptors ignore creation modes and preserve identity',()=>{
  const files=new WorkspaceFiles({'/dir/file':'data'}),fds=new FileDescriptors(files)
  const fd=fds.open(1,'/dir',0,false,0),before=fds.stat(1,fd)
  expect(before.kind).toBe('directory')
  expect(()=>fds.read(1,fd,1)).toThrow(expect.objectContaining({code:'EISDIR'}))
  expect(()=>fds.write(1,fd,new Uint8Array([1]))).toThrow('not writable')
  files.renameSync('/dir','/moved')
  expect(fds.stat(1,fd).ino).toBe(files.statSync('/moved').ino)
  files.rmSync('/moved',{recursive:true})
  expect(fds.stat(1,fd)).toMatchObject({ino:before.ino,kind:'directory',nlink:0})
  fds.close(1,fd);expect(()=>fds.stat(1,fd)).toThrow('EBADF')
  const created=fds.open(1,'/new','w',true,0o600)
  expect(fds.stat(1,created).mode).toBe(0o100600)
  fds.close(1,created)
  files.close()
})

test('numeric flags enforce authority and reject unsupported bits before mutation',()=>{
  const files=new WorkspaceFiles(),fds=new FileDescriptors(files)
  for(const flags of [-1,3,4,NaN,Infinity,2**32,1.5]){
    expect(()=>fds.open(1,'/bad',flags,true)).toThrow('unsupported file open flags')
    expect(files.existsSync('/bad')).toBe(false)
  }
  expect(()=>fds.open(1,'/created',64,false)).toThrow('read-only process')
  expect(files.existsSync('/created')).toBe(false)
  files.writeFileSync('/kept',new Uint8Array([42]))
  expect(()=>fds.open(1,'/kept',512,false)).toThrow('read-only process')
  expect(files.readFileSync('/kept')).toEqual(new Uint8Array([42]))
  expect(fds.size).toBe(0)
})

const bytes=(value:string)=>new TextEncoder().encode(value)
const text=(value:Uint8Array)=>new TextDecoder().decode(value)

test('descriptors have independent positions and positioned IO leaves them unchanged',()=>{
  const files=new WorkspaceFiles({'/a':'abcdef'}),fds=new FileDescriptors(files)
  const a=fds.open(1,'/a','r+',true),b=fds.open(1,'/a','r',false)
  expect(text(fds.read(1,a,2))).toBe('ab')
  expect(text(fds.read(1,a,2,4))).toBe('ef')
  expect(text(fds.read(1,a,2))).toBe('cd')
  expect(text(fds.read(1,b,2))).toBe('ab')
  fds.write(1,a,bytes('X'),0)
  fds.write(1,a,bytes('Y'))
  expect(text(files.readFileSync('/a'))).toBe('XbcdYf')
  fds.truncate(1,a,2)
  fds.write(1,a,bytes('Z'))
  expect([...files.readFileSync('/a')]).toEqual([88,98,0,0,0,90])
  fds.closeOwner(1);expect(fds.size).toBe(0)
})

test('descriptor authority cannot be gained by guessing another process handle',()=>{
  const files=new WorkspaceFiles({'/a':'safe'}),fds=new FileDescriptors(files)
  const fd=fds.open(1,'/a','r+',true)
  for(const operation of [()=>fds.read(2,fd,1),()=>fds.write(2,fd,bytes('x')),
    ()=>fds.truncate(2,fd),()=>fds.stat(2,fd),()=>fds.close(2,fd)])
    expect(operation).toThrow('EBADF')
  expect(text(files.readFileSync('/a'))).toBe('safe')
  fds.closeOwner(2);expect(fds.size).toBe(1)
  fds.closeOwner(1)
  const next=fds.open(2,'/a','r',false)
  expect(next).toBeGreaterThan(fd)
  expect(()=>fds.read(2,fd,1)).toThrow('EBADF')
  expect(()=>fds.write(2,next,bytes('x'))).toThrow('EBADF')
  expect(()=>fds.open(2,'/a','w',false)).toThrow('EACCES')
  expect(text(files.readFileSync('/a'))).toBe('safe')
  fds.closeOwner(2)
})

test('open flags create, truncate, append and reject exclusive symlink targets',()=>{
  const files=new WorkspaceFiles({'/a':'abc'}),fds=new FileDescriptors(files)
  expect(()=>fds.open(1,'/missing','r',true)).toThrow('ENOENT')
  const w=fds.open(1,'/a','w',true)
  expect(fds.stat(1,w).size).toBe(0)
  expect(()=>fds.read(1,w,1)).toThrow('EBADF')
  fds.write(1,w,bytes('a'));fds.close(1,w)
  const a=fds.open(1,'/a','a+',true)
  fds.write(1,a,bytes('b'),0)
  expect(text(fds.read(1,a,2))).toBe('b')
  fds.write(1,a,bytes('c'))
  expect(text(fds.read(1,a,1))).toBe('')
  files.symlinkSync('missing','/link')
  expect(()=>fds.open(1,'/link','wx',true)).toThrow('EEXIST')
  const created=fds.open(1,'/link','w+',true)
  fds.write(1,created,bytes('target'))
  expect(text(files.readFileSync('/missing'))).toBe('target')
  expect(files.readlinkSync('/link')).toBe('missing')
  fds.closeOwner(1)
})

test('descriptor limits fail before creating or truncating a file and recover on close',()=>{
  const files=new WorkspaceFiles({'/a':'keep'}),fds=new FileDescriptors(files,2,1)
  const a=fds.open(1,'/a','r',false)
  expect(()=>fds.open(1,'/a','w',true)).toThrow('EMFILE')
  const b=fds.open(2,'/a','r',false)
  expect(()=>fds.open(3,'/new','w',true)).toThrow('ENFILE')
  expect(files.existsSync('/new')).toBe(false)
  expect(text(files.readFileSync('/a'))).toBe('keep')
  fds.close(1,a)
  const c=fds.open(1,'/a','r',false);expect(c).toBeGreaterThan(b)
  fds.closeOwner(1);fds.closeOwner(2)
})

test('failed writes leave cursor and file unchanged and process cleanup releases orphans',()=>{
  const files=new WorkspaceFiles({'/a':'ab'},3),fds=new FileDescriptors(files)
  const fd=fds.open(1,'/a','r+',true)
  expect(text(fds.read(1,fd,1))).toBe('a')
  expect(()=>fds.write(1,fd,bytes('long'))).toThrow('ENOSPC')
  fds.write(1,fd,bytes('Z'))
  expect(text(files.readFileSync('/a'))).toBe('aZ')
  files.unlinkSync('/a');expect(files.byteLength).toBe(2)
  fds.closeOwner(1);expect(files.byteLength).toBe(0)
  expect(()=>fds.close(1,fd)).toThrow('EBADF')
})
