import {describe,expect,it} from 'vitest'
import {ThreadGroupMailbox} from '../src/sandbox/thread-group-mailbox'

describe('experimental thread group mailbox',()=>{
  it('routes overlapping requests with reordered and duplicate completions',()=>{
    const box=new ThreadGroupMailbox<number,string>(),a=box.createTask(1),b=box.createTask(2)
    const ar=box.park(a),br=box.park(b)
    expect(box.deliver(br,{ok:true,value:20})).toBe(true)
    expect(box.consume(a)).toBeUndefined()
    expect(box.deliver(ar,{ok:false,error:'read failed'})).toBe(true)
    expect(box.deliver(br,{ok:true,value:99})).toBe(false)
    expect(box.consume(b)).toEqual({kind:'result',request:br,result:{ok:true,value:20}})
    expect(box.consume(b)).toBeUndefined()
    expect(box.consume(a)).toEqual({kind:'result',request:ar,result:{ok:false,error:'read failed'}})
    expect(box.deliver(ar,{ok:true,value:99})).toBe(false)
    box.acknowledgeUnwind(ar);box.acknowledgeUnwind(br)
    box.disposeTask(a);box.disposeTask(b);expect(box.pending).toBe(0)
  })
  for(const delivered of [false,true])it(`cancels ${delivered?'after':'before'} delivery without losing the cancellation`,()=>{
    const box=new ThreadGroupMailbox<number,string>(),a=box.createTask(1),request=box.park(a)
    if(delivered)box.deliver(request,{ok:true,value:1})
    expect(box.cancel(a,'stopped')).toBe(true)
    expect(box.cancel(a,'replacement')).toBe(false)
    expect(box.deliver(request,{ok:true,value:2})).toBe(false)
    expect(()=>box.acknowledgeUnwind(request)).toThrow('not been consumed')
    expect(box.consume(a)).toEqual({kind:'cancelled',error:'stopped'})
    expect(box.consume(a)).toBeUndefined()
    expect(()=>box.disposeTask(a)).toThrow('unwind')
    box.acknowledgeUnwind(request);box.disposeTask(a)
  })
  it('preserves cancellation that arrives after result consumption',()=>{
    const box=new ThreadGroupMailbox<number,string>(),a=box.createTask(1),request=box.park(a)
    box.deliver(request,{ok:true,value:1});box.consume(a);box.cancel(a,'stopped')
    expect(()=>box.acknowledgeUnwind(request)).toThrow('not been consumed')
    expect(box.consume(a)).toEqual({kind:'cancelled',error:'stopped'})
    box.acknowledgeUnwind(request)
    expect(()=>box.park(a)).toThrow('cancelled')
    box.disposeTask(a)
  })
  it('rejects stale generations and old request IDs',()=>{
    const box=new ThreadGroupMailbox<number,string>(),old=box.createTask(1),first=box.park(old)
    box.deliver(first,{ok:true,value:1});box.consume(old);box.acknowledgeUnwind(first)
    const second=box.park(old)
    expect(box.deliver(first,{ok:true,value:2})).toBe(false)
    box.cancel(old,'stop');box.consume(old);box.acknowledgeUnwind(second);box.disposeTask(old)
    const current=box.createTask(1),request=box.park(current)
    expect(current.generation).not.toBe(old.generation)
    expect(box.cancel(old,'late')).toBe(false)
    expect(box.deliver(second,{ok:true,value:3})).toBe(false)
    expect(()=>box.consume(old)).toThrow('generation')
    expect(()=>box.acknowledgeUnwind(second)).toThrow('generation')
    expect(box.deliver(request,{ok:true,value:4})).toBe(true)
  })
  it('bounds parked work until unwind, including consumed completions',()=>{
    const box=new ThreadGroupMailbox<number,string>(1),a=box.createTask(1),b=box.createTask(2),request=box.park(a)
    expect(()=>box.park(a)).toThrow('unwind')
    expect(()=>box.park(b)).toThrow('quota')
    expect(()=>box.acknowledgeUnwind(request)).toThrow('consumed')
    box.deliver(request,{ok:true,value:1});box.consume(a)
    expect(()=>box.park(b)).toThrow('quota')
    box.acknowledgeUnwind(request)
    expect(()=>box.acknowledgeUnwind(request)).toThrow('Unknown parked')
    box.park(b);expect(box.pending).toBe(1)
  })
  it('requires an idle cancellation to be consumed before disposal',()=>{
    const box=new ThreadGroupMailbox<number,string>(),a=box.createTask(1)
    box.cancel(a,'stop')
    expect(()=>box.disposeTask(a)).toThrow('Cancellation')
    expect(box.consume(a)).toEqual({kind:'cancelled',error:'stop'})
    box.disposeTask(a)
  })
  it('validates identities and quotas',()=>{
    expect(()=>new ThreadGroupMailbox(0)).toThrow('quota')
    const box=new ThreadGroupMailbox()
    expect(()=>box.createTask(-1)).toThrow('task ID')
    box.createTask(1);expect(()=>box.createTask(1)).toThrow('exists')
  })
})
